<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'MongoDb\Module'                             => __DIR__ . '/Module.php',
  'MongoDb\Collection\AbstractCollection'      => __DIR__ . '/src/MongoDb/Collection/AbstractCollection.php',
  'Application\Service\AbstractModelService'   => __DIR__ . '/src/MongoDb/Service/AbstractModelService.php',
  'MongoDb\Db\AdapterFactory'                  => __DIR__ . '/src/MongoDb/Db/AdapterFactory.php',
  'MongoDb\Db\Exception\InvalidQueryException' => __DIR__ . '/src/MongoDb/Db/Exception/InvalidQueryException.php',
  'MongoDb\Entity\AbstractEntity'              => __DIR__ . '/src/MongoDb/Entity/AbstractEntity.php',
);
