<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'customer/customer/index' => __DIR__ . '/view/customer/customer/index.phtml',
    'customer/customer/show'  => __DIR__ . '/view/customer/customer/show.phtml',
    'template_map'            => __DIR__ . '/view/template_map.php',
);
