<?php
/**
 * Zend Framework Schulung
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zendframeworkschulung.de/
 */

/**
 * Footer view script
 * 
 * @package    Application
 */

$url = $this->url(null, array(), true);
?>
<footer id="footer">
<div class="footer-top"></div>
<div class="container">
<div class="row-fluid">
<div class="span4">
<h4>ZF2 feat. MongoDB</h4>
<p>Mit Hilfe dieses ZF2 Projekts können Sie die Session "Zend Framework 2 feat. MongoDB" im Anschluß noch einmal in Ruhe am eigenen Rechner nachverfolgen. Schauen Sie sich den Code an und probieren Sie selber damit herum.</p>
<p><a href="https://plus.google.com/105130475645941839411" target="_blank">Feedback erwünscht!</a></p>
</div>
<div class="span4">
<h4>Zend Framework Links</h4>
<ul>
<li><a href="http://framework.zend.com/" target="_blank">Zend Framework Website</a></li>
<li><a href="http://zf2.readthedocs.org/" target="_blank">Zend Framework 2 Manual</a></li>
<li><a href="http://modules.zendframework.com/" target="_blank">Zend Framework 2 Module</a></li>
<li><a href="https://github.com/zendframework" target="_blank">Zend Framework GitHub Repository</a></li>
<li><a href="https://github.com/zendframework/zf2/issues" target="_blank">Zend Framework 2 Issue Tracker</a></li>
<li><a href="http://framework.zend.com/docs/api" target="_blank">Zend Framework API Docs</a></li>
</ul> 
</div>
<div class="span4">
<h4>Weitere Links</h4>
<ul>
<li><a href="http://www.zendframeworkschulung.de/" target="_blank">Zend Framework Schulungen</a></li>
<li><a href="http://www.zendframeworkbuch.de/" target="_blank">Zend Framework Buch</a></li>
<li><a href="http://www.zendframeworkmagazin.de/" target="_blank">Zend Framework Magazin</a></li>
<li><a href="https://plus.google.com/105130475645941839411" target="_blank">Google+ Seite Ralf Eggert</a></li>
</ul>
</div>
</div>
</div>
</footer>
