<?php
/**
 * Zend Framework Schulung
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zendframeworkschulung.de/
 */

/**
 * Sidebar view script
 * 
 * @package    Application
 */

$url = $this->url(null, array(), true);
?>
<div class="pull-center well">
Box 1
</div>
<br />
<div class="pull-center well">
Box 2
</div>
