<?php
/**
 * Zend Framework 2 feat. MongoDB
 *
 * Zend Framework Session auf der International PHP Conference 2013 in München
 *
 * @package    Customer
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */
use Customer\Entity\CustomerEntity;

/**
 * namespace definition and usage
 */

/**
 * Index view script
 *
 * @package    Customer
 */

$customerEntity = $this->customerEntity;
/* @var $customerEntity CustomerEntity */

$this->headTitle('Kunde');
$this->pageTitle('Kunde &raquo; ' . $customerEntity->getFirstname() . ' ' . $customerEntity->getLastname());

?>
<table class="table table-striped table-bordered table-hover">
    <tbody>
    <tr>
        <th>Vorname</th>
        <td><?php echo $customerEntity->getFirstname(); ?></td>
    </tr>
    <tr>
        <th>Nachname</th>
        <td><?php echo $customerEntity->getLastname(); ?></td>
    </tr>
    <tr>
        <th>Anschrift</th>
        <td><?php echo
                $customerEntity->getAddress()->getStreet() . ', ' . $customerEntity->getAddress()->getPostcode() . ' ' . $customerEntity
                    ->getAddress()->getCity(); ?></td>
    </tr>
    <tr>
        <th>Land</th>
        <td><?php echo $this->customerCountry($customerEntity); ?></td>
    </tr>
    </tbody>
</table>
<hr/>
<a href="<?php echo $this->url('customer'); ?>" class="btn btn-success">Kundenliste</a>
