<?php
/**
 * Zend Framework 2 feat. MongoDB
 *
 * Zend Framework Session auf der International PHP Conference 2013 in München
 *
 * @package    Customer
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */
use Customer\Form\CustomerForm;

/**
 * namespace definition and usage
 */

/**
 * Update view script
 *
 * @package    Customer
 */

$this->headTitle('Kunde bearbeiten');
$this->pageTitle('Kunde bearbeiten');
$this->headStyle()->appendStyle('label { width: 200px; }');

$form = $this->form;
/* @var $form CustomerForm */
$form->prepare();
$form->setAttribute('action', $this->url('customer/action', array(), true));

echo $this->form($form);
?>
<hr/>
<a href="<?php echo $this->url('customer'); ?>" class="btn btn-success">Kundenliste</a>
